routes/web.php
<?php




Route::get('/', 'HomeController@home');



Route::get('/about-us', 'HomeController@about');

Route::get('/contact-us', 'HomeController@contact');

Route::get('/gallery', 'HomeController@gallery');

Route::get('/gallery1', 'HomeController@gallery1');

Route::get('/academics', 'HomeController@academics');

Route::get('/facilities', 'HomeController@facilities');

Route::get('/activities', 'HomeController@activities');

Route::get('/staffs', 'HomeController@staffs');

Route::get('/management', 'HomeController@management');

Route::get('/students', 'HomeController@students');

Route::get('/norms', 'HomeController@norms');

Route::get('/circular', 'HomeController@circular');

Route::get('/annual-report', 'HomeController@annualreport');

Route::get('/beyond-academics', 'HomeController@beyondacademics');

Route::get('/gallery2', 'HomeController@gallery2');


Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');
Route::get('/dashboard', 'HomeController@dashboard');
Route::resource('/organizations', 'OrganizationController');
Route::get('/profile','OrganizationController@profile')->name('profile');
Route::post('/profile','OrganizationController@update_profile')->name('profile.update');
Route::get('/changepassword','OrganizationController@changepassword')->name('changepassword');
Route::post('/password', 'OrganizationController@password')->name('password');
Route::resource('/albums','AlbumController');
Route::resource('/photos','PhotoController');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
	<head>
		<title>Vijaya Higher Primary School</title>
       	<link rel="shortcut icon" href="{{ asset ('img/fav.png') }}" type="image/x-icon">
    	<link rel="icon" href="{{ asset ('img/fav.png') }}" type="image/x-icon">
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		
		<link href="{{ asset('admin/css/bootstrap.min.css') }}" rel="stylesheet">
		<link href="{{ asset('admin/css/style.css') }}" rel="stylesheet">
		<link rel="stylesheet" href="{{ asset('vendors/dropify/dist/css/dropify.min.css') }}">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
		<link rel="stylesheet" type="text/css" href=" https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css ">
		<script src="http://cdn.ckeditor.com/4.6.1/standard/ckeditor.js"></script>
		 <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

        <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
	</head>
    <body>
		<nav class="navbar navbar-default">
		    <div class="container">
				<div class="navbar-header">
				    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
				  	</button>
				  	<a class="navbar-brand" href="#">Vijaya Higher Primary School</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
				    <ul class="nav navbar-nav">
						<li class=""><a href="{{ url('/dashboard') }}">Dashboard</a></li>
						<li><a href="{{ route('organizations.index')}}">Organization</a></li>
			            <li><a href="{{ route('albums.index') }}">Albums</a></li>
				  	</ul>
				    <ul class="nav navbar-nav navbar-right">
					  	@guest
			                <li><a href="{{ route('login') }}">Login</a></li>
			            @else
			            <div class="dropdown create">
			                <a class="btn btn-default dropdown-toggle" type="button"  data-toggle="dropdown"  aria-expanded="true">
			                 	<span>{{ Auth::user()->name }}</span> 
			                 	 <img src="{{ asset('/storage/user/'.Auth::User()->avatar) }}" width="25px" height="20px;" class="img-circle">
			                	<span class="caret"></span>
			            	</a>
			              <ul class="dropdown-menu" >
			               <li>
			                	<a type="button" href="{{ route('profile') }}" >
			                	    <i class="glyphicon glyphicon-user">.</i> 
	                                Profile
	                            </a>
	                        </li>
	                        <li>
	                        	<a type="button" href="{{ route('changepassword') }}" > 
	                        		<i class="glyphicon glyphicon-lock"></i>
	                                Change Password
	                            </a>
	                        </li>
	                         <li>
								<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
										<i class="glyphicon glyphicon-log-out"></i>
											Logout
									<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
					                    @csrf
					                </form>
				            	</a>
				            </li>
				        </ul>
			            </div>
				        @endif
				  	</ul>
				</div>
		  	</div>
		</nav>
		@yield('content')
		<footer id="footer">
            <div class="container ">
                <div class="center-text">
                    <center class="text-white">
                        <p>© Designed &amp; Developed By <a style="color: #000" href="http://mdbstech.com" target="_blank"> MDBS Tech Pvt. Ltd.</a>
                        </p>
                    </center>
                </div>
            </div>
        </footer>
		<script>
			 CKEDITOR.replace( 'description' );
		</script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="{{ asset('admin/js/bootstrap.min.js') }}"></script>
		<script src="{{ asset('vendors/dropify/dist/js/dropify.min.js') }}"></script>
		<script>
           $(' .dropify').dropify();
            
    </script>
     <script>
            function convertToSlug(from,to)
            {
                 var from_text = $('#' + from).val(); 
                 var to_text = from_text
                    .toLowerCase()
                    .replace('&','and')
                    .replace(/ /g,'-')
                    .replace(/[^\w-]+/g,'');
                    $('#'+to).val(to_text);
            }
        </script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
        <script type="text/javascript">
            $(function (){
                $('.select2').select2({
                    theme: 'bootstrap4',
                });
            });

        </script>
   
		 @yield('js')
    </body>
</html>

resources/views/admin/layouts/message.blade.php
@if(session()->has('success'))
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ session()->get('success') }}
    </div>
@endif

@if(session()->has('error'))
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ session()->get('error') }}
    </div>
@endif

resources/views/admin/layouts/sidebar.blade.php
<div class="col-md-3">
  <div class="list-group">
      <a href="index.html" class="list-group-item active main-color-bg">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Dashboard
      </a>
      <a href="{{ route('organizations.index')}}" class="list-group-item">
        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Organizations
      </a>
      <a href="{{ route('profile')}}" class="list-group-item">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Profile
      </a>
      <a href="{{ route('changepassword')}}" class="list-group-item">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Chang Password
      </a>
      <a href="{{route('albums.index')}}" class="list-group-item">
        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span> Albums
      </a>
  </div>
</div>

resources/views/admin/layouts/test.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>