routes/web.php
<?php




Route::get('/', 'HomeController@home');



Route::get('/about-us', 'HomeController@about');

Route::get('/contact-us', 'HomeController@contact');

Route::get('/gallery', 'HomeController@gallery');

Route::get('/gallery1', 'HomeController@gallery1');

Route::get('/academics', 'HomeController@academics');

Route::get('/facilities', 'HomeController@facilities');

Route::get('/activities', 'HomeController@activities');

Route::get('/staffs', 'HomeController@staffs');

Route::get('/management', 'HomeController@management');

Route::get('/students', 'HomeController@students');

Route::get('/norms', 'HomeController@norms');

Route::get('/circular', 'HomeController@circular');

Route::get('/annual-report', 'HomeController@annualreport');

Route::get('/beyond-academics', 'HomeController@beyondacademics');

Route::get('/gallery2', 'HomeController@gallery2');


Auth::routes();

Route::get('/home', 'HomeController@home')->name('home');
Route::get('/dashboard', 'HomeController@dashboard');
Route::resource('/organizations', 'OrganizationController');
Route::get('/profile','OrganizationController@profile')->name('profile');
Route::post('/profile','OrganizationController@update_profile')->name('profile.update');
Route::get('/changepassword','OrganizationController@changepassword')->name('changepassword');
Route::post('/password', 'OrganizationController@password')->name('password');
Route::resource('/albums','AlbumController');
Route::resource('/photos','PhotoController');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
   protected $fillable = [
        'title','slug','description','poster'
    ];
    protected $primaryKey = 'album_id';

    public function Photos()
    {
    	return $this->hasMany('App\Photo','album_id','album_id');
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;
use Image;
use App\Album;
use Illuminate\Http\Request;

use App\Photo;

class AlbumController extends Controller
{
    public function __construct() 
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        $albums = Album::get();
        return view('admin.album.index',compact('albums'));
    }

    public function create()
    {
        return view('admin.album.create');
    }

    public function store(Request $request)
    {
        $data = $this->validate($request, [
                'title' => 'required|max:150',
                'slug' => 'required|max:100|unique:albums',               
                'description' => 'nullable',
                'poster' => 'required',
            ]);
           if($request->hasFile('poster'))
            {
                $file = $request->file('poster');
                $filename = date('Ymdhis'). '.' . $file->getClientOriginalExtension();
                Image::make($file)->save(public_path('/storage/album/'.$filename));
                $data['poster'] = $filename;
            }

            $album = Album::create($data);
            return redirect()->route('albums.index')->with('success','Album is successfully created...!');
    }
    
    public function show(Album $album)
    {
         $images = Photo::where('album_id',$album->album_id)->get();
        return view('admin.album.show',compact('images','album'));
    }

    public function edit(Album $album)
    {
        return view('admin.album.edit',compact('album'));
    }
   
    public function update(Request $request, Album $album)
    {
        $data = $this->validate($request, [
            'title' => 'required|max:150',
            'slug' => 'required|max:150|unique:albums,slug,'.$album->album_id.',album_id',
            'description' => 'nullable',
            'poster' => 'nullable',
        ]);
       if($request->hasFile('poster'))
        {
            $file = $request->file('poster');
            $filename = date('Ymdhis'). '.' . $file->getClientOriginalExtension();
            Image::make($file)->save(public_path('/storage/album/'.$filename));
            $data['poster'] = $filename;
        }
        Album::where('album_id',$album->album_id)->update($data);
        return redirect()->route('albums.index')->with('success','Album is successfully updated...!');
    }
    
    public function destroy(Album $album)
    {
        Album::where('album_id',$album->album_id)->with('Image')->delete();
        session()->flash('success', 'Album is successfully deleted...!!');
    }
}

resources/views/admin/album/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Albums</h1>
                </div>
                <div class="col-md-2 text-right">
                    <div class="create">
                        <a href="{{ route('albums.index') }}" class="btn btn-sm  btn-success" type="button">
                            <i class="glyphicon glyphicon-list"></i>
                                Albums
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section id="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i>
                    Dashboard
                </li>
                <li class="active">
                    Albums
                </li>
            </ol>
        </div>
    </section>
    <section id="main">
        <div class="container">
            <div class="row">
            @include('admin.layouts.sidebar')
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading main-color-bg">
                            <h3 class="panel-title">New Album</h3>
                        </div>
                        <div class="panel-body">
                        @include('admin.layouts.message')
                            <form class="row" method="post" action="{{ route('albums.store') }}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                                <div class="col-sm-4">
                                    <div class="panel panel-default">
                                      
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <input type="file" name="poster" class="dropify @error('poster') is-invalid @enderror" data-default-file="{{ asset('storage/album/poster.png') }}">
                                                            @error('poster')
                                                                <span class="invalid-feedback" role="alert">
                                                                    <strong>{{ $message }}</strong>
                                                                </span>
                                                            @enderror
                                                        </div>
                                                    </div> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-8">
                                        <div class="row">
                                           <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label for="title">Title *</label>
                                                   <input name="title" id="title" class="form-control @error('title') is-invalid @enderror" type="text" placeholder="Title" autofocus value="{{ old('title') }}" onkeyup="convertToSlug('title','slug')">
                                                    @error('title')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                             <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label for="slug">Slug *</label>
                                                     <input name="slug" id="slug" class="form-control @error('slug') is-invalid @enderror" type="text" placeholder="Slug" value="{{ old('slug') }}" readonly>
                                                    @error('slug')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                             <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="description">Description </label>
                                                    <textarea name="description" class="form-control @error('description') is-invalid @enderror" type="text" placeholder="Description" value="{{old('description')}}"></textarea>
                                                    @error('description')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                    <div class="pull-right">  
                                        <a href="{{ route('albums.index')}}" class="btn btn-sm btn-danger mr-2">
                                            <i class="glyphicon glyphicon-ban-circle"></i> Discard
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-primary">
                                            <i class="glyphicon glyphicon-send"></i>
                                                Submit
                                        </button>
                                    </div>                                              
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/album/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Albums</h1>
                </div>
                <div class="col-md-2 text-right">
                    <div class="create">
                        <a href="{{ route('albums.index') }}" class="btn btn-sm  btn-success" type="button">
                            <i class="glyphicon glyphicon-list"></i>
                                Albums
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section id="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i>
                    Dashboard
                </li>
                <li class="active">
                    Albums
                </li>
            </ol>
        </div>
    </section>
    <section id="main">
        <div class="container">
            <div class="row">
            @include('admin.layouts.sidebar')
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading main-color-bg">
                            <h3 class="panel-title">Update Album</h3>
                        </div>
                        <div class="panel-body">
                        @include('admin.layouts.message')
                            <form class="row" method="post" action="{{ route('albums.update',$album->album_id ) }}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                                <div class="col-sm-4">
                                    <div class="panel panel-default">
                                        <div class="panel-heading main-color-bg">
                                            Poster
                                        </div>
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <input type="file" name="poster" class="dropify @error('poster') is-invalid @enderror" data-default-file="{{ asset('/storage/album/'.$album->poster) }}">
                                                            @error('poster')
                                                                <span class="invalid-feedback" role="alert">
                                                                    <strong>{{ $message }}</strong>
                                                                </span>
                                                            @enderror
                                                        </div>
                                                    </div> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-8">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label for="title">Title *</label>
                                                    <input name="title" id="title" class="form-control @error('title') is-invalid @enderror" type="text" placeholder="Title" value="{{ $album->title }}" autofocus onkeyup="convertToSlug('title','slug')">
                                                    @error('title')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                             </div>
                                             <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label for="slug">Slug *</label>
                                                    <input name="slug" id="slug" class="form-control @error('slug') is-invalid @enderror" type="text" placeholder="Slug" value="{{ $album->slug }}" readonly>
                                                    @error('slug')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                             <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="description">Description </label>
                                                    <textarea name="description" id="description"class="form-control  @error('description') is-invalid @enderror" type="text" placeholder="Description" value="{{ $album->description}}">{{ $album->description}}</textarea>
                                                    @error('description')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                    <div class="pull-right">  
                                        <a href="{{ route('albums.index')}}" class="btn btn-sm btn-danger mr-2">
                                            <i class="glyphicon glyphicon-ban-circle"></i> Discard
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-primary">
                                            <i class="glyphicon glyphicon-send"></i>
                                                Update
                                        </button>
                                    </div>                                              
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/album/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Albums</h1>
                </div>
                <div class="col-md-2 text-right">
                    <div class="create ">
                        <a href="{{ route('albums.create') }}" class="btn btn-sm  btn-success" type="button">
                            <i class="glyphicon glyphicon-plus"></i>
                                New Album
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section id="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i>
                    Dashboard
                </li>
                <li class="active">
                    Albums
                </li>
            </ol>
        </div>
    </section>
    <section id="main">
        <div class="container">
            <div class="row">
                @include('admin.layouts.sidebar')
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading main-color-bg">
                            <h3 class="panel-title">Albums</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                @foreach($albums as $album)
                                    <div class="col-sm-4 pb-3">
                                        <div class="panel panel-default">
                                            <img class="panel-img-top" src="{{ asset('storage/album/'.$album->poster) }}" height="200px" width="251px" alt="{{ $album->title }}">
                                            <div class="panel-body">
                                                <h5 class="panel-title">{{ $album->title }}</h5>
                                                <p class="panel-text">{!! str_limit($album->description, 80) !!}</p>
                                            </div>
                                            <div class="panel-footer text-muted text-center">
                                                <a href="{{ route('albums.show',$album->album_id) }}" class="btn btn-xs btn-primary">
                                                    <i class='glyphicon glyphicon-plus'></i>
                                                    Images
                                                </a>
                                                <a href="{{ route('albums.edit',$album->album_id) }}" class="btn btn-xs btn-success">
                                                     <i class='glyphicon glyphicon-pencil'></i>
                                                    Edit
                                                </a>
                                                <button onclick="destroy({{ $album->album_id }})" type="button" class="btn btn-xs btn-danger">
                                                     <i class='glyphicon glyphicon-trash'></i>
                                                    Delete
                                                </button>
                                             </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('js')
    <script type="text/javascript">
        function destroy(album_id) 
        {
            if(confirm('Do you want to Continue...?'))
            {
                $.ajax({
                    method: 'DELETE',
                    url: "{{ route('albums.destroy','album_id') }}".replace('album_id',album_id),
                    data: {
                        _token: '{{ Session::token() }}'
                    },
                    success: function(data)
                    {
                        window.location='{{ route("albums.index") }}';
                    },
                    error: function(data)
                    {
                        console.log(data);
                    }
                });
            }
        }
    </script>
@endsection

resources/views/admin/album/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Albums</h1>
                </div>
                <div class="col-md-2 text-right">
                    <div class="create">
                        <a href="{{ route('albums.index') }}" class="btn btn-sm  btn-success" type="button">
                            <i class="glyphicon glyphicon-list"></i>
                                Albums
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section id="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i>
                    Dashboard
                </li>
                <li class="active">
                    Albums
                </li>
            </ol>
        </div>
    </section>
    <section id="main">
       <div class="container">
            <div class="row">
                @include('admin.layouts.sidebar')
                <div class="col-md-9">
                    <div class="panel panel-default">
                    @include('admin.layouts.message')
                        {{-- <div class="panel-heading main-color-bg">
                            <h3 class="panel-title">Images</h3>
                        </div> --}}
                        <div class="panel-body">
                            <form class="col-sm-4" method="post" action="{{ route('photos.store') }}" autocomplete="off" enctype="multipart/form-data">
                                @csrf
                                <div class="panel panel-default">
                                    <div class="panel-heading main-color-bg">
                                        New Image
                                    </div>
                                    <div class="">
                                        <input type="hidden" name="album_id" value="{{ $album->album_id }}">
                                        <div class="form-group">
                                            <input type="file" id="images" name="images[]" class="dropify @error('title') is-invalid @enderror" multiple>
                                            @error('images')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>  
                                    </div>
                                    <div class="panel-footer">
                                        <div class="float-right"> 
                                            <a href="{{ route('albums.index')}}" class="btn btn-sm btn-danger ">
                                                <i class="glyphicon glyphicon-ban-circle"></i> Discard
                                            </a>
                                            <button type="submit" class="btn btn-sm btn-primary">
                                                <i class="glyphicon glyphicon-send"></i>
                                                Submit
                                            </button>
                                        </div>                                              
                                    </div>
                                </div>
                            </form>
                            <div class="col-sm-8">
                                <div class="panel panel-default">
                                    <div class="panel-heading main-color-bg ">
                                        Images
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            @foreach($images as $image)
                                                <div class="col-sm-4">
                                                    <div class="panel panel-default">
                                                        <img class="panel-img-top" src="{{ asset('storage/photos/'.$image->image) }}" alt="{{ $image->title }}" height="130px" width="140px">
                                                        <div class="panel-footer">
                                                            <button onclick="destroy({{ $image->photo_id }})" type="button" class="btn btn-sm btn-block btn-danger">
                                                                 <i class='glyphicon glyphicon-trash'></i>
                                                                Delete
                                                            </button>
                                                         </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('js')
    <script type="text/javascript">
        function destroy(photo_id) 
        {
            if(confirm('Do you want to Continue...?'))
            {
                $.ajax({
                    method: 'DELETE',
                    url: "{{ route('photos.destroy','photo_id') }}".replace('photo_id',photo_id),
                    data: {
                        _token: '{{ Session::token() }}'
                    },
                    success: function(data)
                    {
                        location.reload();
                    },
                    error: function(data)
                    {
                        console.log(data);
                    }
                });
            }
        }
    </script>
@endsection